# The Schnack docker image that I've defined require 2 persistent
# volume mounts, 1 to store the data and the other one stores
# the configuration. The user ID that is running Schnack must
# have read-write access to the data and read access to the config
# This example defines the data volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-schnack-data
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: /schnack/data
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
#  nfs:       -- NFS example, assuming you already have an NFS export
#    server: node.example.com
#    path: "/exports/comments/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-schnack-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: pv-schnack-data
  resources:
    requests:
      storage: 1G
