apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
# IP Address range to be used for load balancing
      - 192.168.xxx.yyy-192.168.xxx.zzz
